<?php if($this->clientList != NULL){ ?>
    
    <table class='spreadsheet' cellpadding='0' cellspacing='0'>
    <tr>
        <th>خيارات</th>
        <th>اسم العميل</th>
        <th>البريد الالكترونى</th>
        <th>عنوان العميل</th>
    </tr>
    <?php echo $this->partialLoop('partials/_client-row.phtml', $this->clientList); ?>
</table>

<?php }else{ ?> 
    
    <p>لا يوجد عملاء مسجلين فى النظام</p>
    
<?php } ?>
    
    <p class=""><a href='create/'>اضافة عميل جديد</a></p>

